# Generated by Django 3.2 on 2022-01-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_resourceseat_resourceseattemplate_resourcetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('address', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counter.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessResourceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.businesstype')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_letter', models.CharField(max_length=1, null=True)),
                ('name', models.CharField(max_length=40)),
                ('capacity', models.IntegerField(null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.business')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counter.resourcetype')),
            ],
        ),
    ]
