# Generated by Django 3.2 on 2022-01-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_business_businessresource_businessresourceoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='category',
            new_name='business_type',
        ),
        migrations.AlterField(
            model_name='resourceseat',
            name='seat_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='counter.resourceseattemplate'),
        ),
    ]
