# Generated by Django 3.2 on 2022-01-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20220116_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='resource_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='counter.resourcetype'),
            preserve_default=False,
        ),
    ]
