# Generated by Django 3.2 on 2022-03-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0010_auto_20220327_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleroute',
            name='business',
        ),
    ]
