# Generated by Django 3.2 on 2022-04-12 04:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_rename_vehiclestops_vehiclestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 12, 4, 5, 37, 346990))),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.businessresource')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicleroute',
            name='end_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endpoint', to='counter.vehiclestop'),
        ),
        migrations.AlterField(
            model_name='vehicleroute',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startpoint', to='counter.vehiclestop'),
        ),
        migrations.DeleteModel(
            name='VehicleTimeTable',
        ),
        migrations.AddField(
            model_name='vehiclequeue',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.vehicleroute'),
        ),
    ]
