# Generated by Django 3.2 on 2022-04-12 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_auto_20220412_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerouteratetemplate',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='counter.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclequeue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 4, 24, 29, 842406)),
        ),
    ]
