# Generated by Django 3.2 on 2022-04-17 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0015_auto_20220417_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclequeue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 4, 6, 23, 989917, tzinfo=utc)),
        ),
    ]
