# Generated by Django 3.2 on 2022-04-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_alter_vehiclequeue_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRouteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.business')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.vehicleroute')),
            ],
            options={
                'unique_together': {('business', 'route')},
            },
        ),
    ]
