# Generated by Django 3.2 on 2022-04-17 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0018_vehiclerouterate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSeatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('column_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.FloatField()),
                ('route_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.vehiclerouterate')),
            ],
            options={
                'unique_together': {('route_rate', 'row_number', 'column_number')},
            },
        ),
    ]
