# Generated by Django 3.2 on 2022-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0020_auto_20220424_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclequeue',
            name='route',
        ),
    ]
