# Generated by Django 3.2 on 2022-04-25 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0021_remove_vehiclequeue_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerouterate',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
