# Generated by Django 3.2 on 2022-04-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0023_alter_vehiclerouterate_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerouterate',
            name='estimated_duration',
        ),
    ]
