# Generated by Django 3.2 on 2022-04-25 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0024_remove_vehiclerouterate_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerouterate',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), null=True),
        ),
    ]
