# Generated by Django 3.2 on 2022-05-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0025_vehiclerouterate_estimated_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclequeue',
            old_name='resource',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='vehicleseatrate',
            old_name='column_number',
            new_name='column_index',
        ),
        migrations.RenameField(
            model_name='vehicleseatrate',
            old_name='row_number',
            new_name='row_index',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleseatrate',
            unique_together={('route_rate', 'row_index', 'column_index')},
        ),
    ]
