# Generated by Django 3.2 on 2022-05-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0026_auto_20220510_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending ')], default='Pending', max_length=80)),
                ('starting_from', models.DateTimeField()),
                ('ending_to', models.DateTimeField()),
                ('charged_amount', models.IntegerField()),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=520)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.businessresource')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('column_index', models.IntegerField()),
                ('is_disabled', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='counter.booking')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.vehiclequeue')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter.user'),
        ),
    ]
