# Generated by Django 3.2 on 2022-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0029_auto_20220730_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestop',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
