# Generated by Django 3.2 on 2022-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0030_alter_vehiclestop_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmembership',
            name='is_front_office_personnel',
        ),
        migrations.RemoveField(
            model_name='businessmembership',
            name='is_support_personnel',
        ),
        migrations.AddField(
            model_name='businessdepartment',
            name='is_front_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
