# Generated by Django 3.2 on 2022-07-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0032_resourceseat_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='counter.businessdepartment')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='counter.vehicleroute')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSeatInlinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.routeseatprice')),
            ],
        ),
    ]
