# Generated by Django 3.2 on 2022-07-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0033_routeseatinlineprice_routeseatprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeseatprice',
            name='department',
        ),
        migrations.AddField(
            model_name='routeseatprice',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='counter.business'),
            preserve_default=False,
        ),
    ]
