# Generated by Django 3.2 on 2022-07-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0034_auto_20220730_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeseatprice',
            name='resource_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='counter.resourcetype'),
            preserve_default=False,
        ),
    ]
