# Generated by Django 3.2 on 2022-07-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0035_routeseatprice_resource_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteSeatPrice',
            new_name='RoutePlan',
        ),
    ]
